name = "ATGVP_Dev"
version = "DEV-1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7bd737a5c1fb731d8ddf3c14bcb2654bdb2a427d2d256c8eb6eb2bd0cf822a0"

[versions]
fabric = "0.18.3"
minecraft = "1.21.10"
