# Determines long the Happy Ghast has to fly forward until it gets a speed boost
seconds_until_boost = 4

# Determines how much faster the ghast moves when flying forward while boosted
forward_multiplier = 2.0

# Determines how much faster the ghast moves when flying with Speed I
potion_multiplier = 2.5

# Determines how much faster the ghast moves when flying with Speed II
potion_multiplier_two = 3.5

# Determines whether HUD debug overlay will display while riding Happy Ghast
debugging = false

# Client: Determines whether boost overlay will display while riding Happy Ghast
display_boost_bar = true
